project:
  type: website
  output-dir: docs

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
    
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
    
  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSiteAuth.xml"
    - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"
    - "pgp_ath.asc.txt"  

freeze: true

bibliography: files/bib/references.bib

# Metadata stuff
pagetitle: "{{< meta title >}} | Usman Afzali, PhD"
author-meta: "Usman Afzali"

icon: fa-book

website:
  title: "Usman Afzali, PhD"
  description: "Usman Afzali is a postdoc at University University, researching human flourishing and teaching neuroscience, methods & statistics."
  favicon: "/files/usman.jpeg"
  site-url: "https://github.com/usman-afzali/web2"
  repo-url: "https://github.com/usman-afzali/web2"
  
  twitter-card: 
    image: "/files/usman.jpeg"
    card-style: summary_large_image
    creator: "@UsmanAfzali"
    site: "@UsmanAfzali"
    
  open-graph: 
    image: "/files/usman.jpeg"
    locale: en_US  
  
  navbar:
    pinned: true
    
    left: 
      - text: About
        href: about.qmd
      - text: CV
        href: cv/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Postdoc
        file: postdoc/index.qmd
      - text: Research
        file: research/index.qmd
      - text: Supervision
        file: supervision/index.qmd
      - text: Teaching
        href: teaching/index.qmd        

    right:
      - text: "{{< fa user-secret >}}"
        href: https://www.canterbury.ac.nz/research/about-uc-research/research-specialities-and-projects/research-projects/the-muslim-diversity-study
        target: "_blank"        
      - text: "{{< fa building-columns >}}"
        href: https://profiles.canterbury.ac.nz/10070-usman-afzali
        target: "_blank"        
      - icon: envelope
        aria-label: email
        href: "mailto:usman.afzali@canterbury.ac.nz"  
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0001-5119-9388
        target: "_blank"        
      - icon: github
        aria-label: github
        href: https://github.com/usman-afzali
        target: "_blank"        
      - text: G
        href: https://scholar.google.com/citations?user=7avlCwUAAAAJ&hl=en&oi=ao
        target: "_blank"        
      - text: O
        href: https://osf.io/ejyn2/
        target: "_blank"        
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Usman-Afzali
        target: "_blank"        
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/usman-afzali
        target: "_blank"        
      - icon: twitter
        href: https://twitter.com/UsmanAfzali
        target: "_blank"
      - text: "{{< fa brands youtube >}}"
        href: https://www.youtube.com/@UsmanAfzali
        target: "_blank"

  page-footer:
      left: |
        <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Usman Afzali</span>
        <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      center: |
        <span class="faux-block">All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>
        <span class="faux-block">[Adapted from Andrew Heiss](https://github.com/andrewheiss/ath-quarto)</span>
      right: |
        <span class="faux-block">Made with {{< fa brands r-project >}} and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)</span>
        <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
      
format:
  html:
    theme: 
      - html/ath.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai