---
title: Reserach Supervision
date: 2024-06-17
date-modified: 2024-06-17
description-meta: Usman Afzali is the principal investigator (lead researcher) of the Muslim Diversity Study.
title-block-banner: "magenta"
published-title: Last updated
toc: true
toc-location: right
toc-title: "Contents"
---

I have been supervising research students since the beginning of 2021. Due to not being a continuing/permanent staff member, I can only co-supervise Master's or PhD students, even if I take over a large amount of supervision responsibility.

## Ongoing

:::: {.columns}

::: {.column width="5%"}
1
:::

::: {.column width="10%"}
2024 -- Present
:::

::: {.column width="15%"}
A. Bello
:::

::: {.column width="15%"}
PhD in Data Science
:::

::: {.column width="40%"}
Effects of interaction with a dog on the brain and non-brain activity using mobile brain/body imaging (MoBI)
:::

::: {.column width="15%"}
Associate supervisor
:::
::::


:::: {.columns}

::: {.column width="5%"}
2
:::

::: {.column width="10%"}
2024 -- Present
:::

::: {.column width="15%"}
J. Badis
:::

::: {.column width="15%"}
BA Hons Psychology
:::

::: {.column width="40%"}
Predictors of Islamophobia in New Zealand: Findings from the New Zealand Attitudes and Values Study
:::

::: {.column width="15%"}
`Primary supervisor`
:::
::::


:::: {.columns}

::: {.column width="5%"}
3
:::

::: {.column width="10%"}
2023 -- Present
:::

::: {.column width="15%"}
K. Johnson
:::

::: {.column width="15%"}
PhD in Psychology
:::

::: {.column width="40%"}
Biomarkers for Early Dementia: Memory suppression, language comprehension and EEG
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

## Completed

:::: {.columns}

::: {.column width="5%"}
4
:::

::: {.column width="10%"}
2023 -- 2024
:::

::: {.column width="15%"}
N. Shadbolt
:::

::: {.column width="15%"}
BA Hons Psychology
:::

::: {.column width="40%"}
The Effects of Partial Sleep Deprivation on Memory Suppression
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

:::: {.columns}

::: {.column width="5%"}
5
:::

::: {.column width="10%"}
2023
:::

::: {.column width="15%"}
H. Grace
:::

::: {.column width="15%"}
BA Hons Psychology
:::

::: {.column width="40%"}
The Construction and Validation of The Contemplative Experience Scale
:::

::: {.column width="15%"}
`Primary supervisor`
:::
::::

:::: {.columns}

::: {.column width="5%"}
6
:::

::: {.column width="10%"}
2023
:::

::: {.column width="15%"}
R. Heaton
:::

::: {.column width="15%"}
BA Hons Psychology
:::

::: {.column width="40%"}
Investigating the Effects of Sleep Deprivation on Memory Suppression Tasks
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

:::: {.columns}

::: {.column width="5%"}
7
:::

::: {.column width="10%"}
2022
:::

::: {.column width="15%"}
K. Johnson
:::

::: {.column width="15%"}
BSc Hons Psychology
:::

::: {.column width="40%"}
Testing the Think/No-Think Effect with Same and Independent Cues: Conditionalised Versus Unconditionalised Recall
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

:::: {.columns}

::: {.column width="5%"}
8
:::

::: {.column width="10%"}
2022
:::

::: {.column width="15%"}
P. Theobald
:::

::: {.column width="15%"}
BSc Hons Psychology
:::

::: {.column width="40%"}
Actively Forgetting Unwanted Memories: An Inhibitory Account of the Think No/Think Paradigm
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

:::: {.columns}

::: {.column width="5%"}
9
:::

::: {.column width="10%"}
2022
:::

::: {.column width="15%"}
J. Auckram
:::

::: {.column width="15%"}
BSc Hons Psychology, Victoria University of Wellington
:::

::: {.column width="40%"}
Powering Through Struggles: Resilience of Muslim Women in Ōtautahi/Christchurch During Covid-19 Lockdowns
:::

::: {.column width="15%"}
Research mentor
:::
::::

:::: {.columns}

::: {.column width="5%"}
9
:::

::: {.column width="10%"}
2021 -- 2022
:::

::: {.column width="15%"}
D. Matchett
:::

::: {.column width="15%"}
MSc Psychology
:::

::: {.column width="40%"}
Memory Suppression under Sleep Deprivation: The Effects of Sleep Loss and Sleep Time on Suppressing Unwanted Memories
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

:::: {.columns}

::: {.column width="5%"}
11
:::

::: {.column width="10%"}
2021
:::

::: {.column width="15%"}
J. Lynskey
:::

::: {.column width="15%"}
BSc Hons Psychology
:::

::: {.column width="40%"}
Memory Suppression in Those Susceptible to PTSD - A Study Adopting the Think/No-Think Paradigm
:::

::: {.column width="15%"}
Co-supervisor
:::
::::

:::: {.columns}

::: {.column width="5%"}
12
:::

::: {.column width="10%"}
2021
:::

::: {.column width="15%"}
J. Newlands
:::

::: {.column width="15%"}
BSc Hons Psychology
:::

::: {.column width="40%"}
Does OCD Impact One’s Ability to Actively Suppress Memories? A Think/No-Think Paradigm Study
:::

::: {.column width="15%"}
Co-supervisor
:::
::::